# Generated by Django 4.2.3 on 2024-09-14 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_camisa', models.IntegerField()),
                ('posicao', models.CharField(choices=[('GOL', 'Goleiro'), ('DEF', 'Defensor'), ('MEI', 'Meio-campo'), ('ATA', 'Atacante')], max_length=3)),
                ('cartoes_amarelos', models.IntegerField(default=0)),
                ('cartao_vermelho', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('jogadores_banco', models.ManyToManyField(related_name='banco', to='app1.jogador')),
                ('jogadores_titulares', models.ManyToManyField(related_name='titulares', to='app1.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField()),
                ('jogador_entrou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrou', to='app1.jogador')),
                ('jogador_saiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saiu', to='app1.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_casa', models.IntegerField(default=0)),
                ('placar_visitante', models.IntegerField(default=0)),
                ('tempo_primeiro_tempo', models.DurationField(default=datetime.timedelta(seconds=2700))),
                ('acrescimo_primeiro_tempo', models.DurationField(default=datetime.timedelta(0))),
                ('tempo_segundo_tempo', models.DurationField(default=datetime.timedelta(seconds=2700))),
                ('acrescimo_segundo_tempo', models.DurationField(default=datetime.timedelta(0))),
                ('tempo_jogo_total', models.DurationField(default=datetime.timedelta(0))),
                ('tempo_paralisado', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('PARALISADA', 'Paralisada'), ('INTERVALO', 'Intervalo'), ('FINALIZADA', 'Finalizada')], default='EM_ANDAMENTO', max_length=15)),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='app1.competicao')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_casa', to='app1.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_visitante', to='app1.time')),
            ],
        ),
        migrations.AddField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.time'),
        ),
    ]
