# Generated by Django 4.2.3 on 2024-09-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_jogador_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='jogadores_banco',
            field=models.ManyToManyField(blank=True, null=True, related_name='banco', to='app1.jogador'),
        ),
    ]
