# Generated by Django 4.2.3 on 2024-09-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_time_jogadores_banco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='acrescimo_primeiro_tempo',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='acrescimo_segundo_tempo',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='tempo_jogo_total',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='tempo_paralisado',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='tempo_primeiro_tempo',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='tempo_segundo_tempo',
        ),
    ]
