# Generated by Django 4.2.3 on 2024-09-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_partida_acrescimo_primeiro_tempo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituicao',
            name='tempo',
        ),
    ]
