# Generated by Django 4.2.3 on 2024-09-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_substituicao_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='total_gols',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='substituicao',
            name='tempo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols_partida', to='app1.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='app1.partida')),
            ],
        ),
    ]
