# Generated by Django 4.2.3 on 2024-09-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_jogador_total_gols_substituicao_tempo_time_sigla_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Substituicao',
        ),
    ]
