# Generated by Django 4.2.3 on 2024-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_substituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='gol_contra',
            field=models.BooleanField(default=False),
        ),
    ]
