# Generated by Django 4.2.3 on 2024-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_gol_gol_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='gol_tipo',
            field=models.CharField(blank=True, choices=[('CASA', 'casa'), ('VISITANTE', 'visitante')], max_length=15, null=True),
        ),
    ]
