# Generated by Django 4.2.3 on 2024-09-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_gol_gol_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cartao', models.CharField(blank=True, choices=[('AMARELO', 'Amarelo'), ('VERMELHO', 'Vermelho')], max_length=15, null=True)),
                ('lado_cartao', models.CharField(blank=True, choices=[('CASA', 'Casa'), ('VISITANTE', 'Visitante')], max_length=15, null=True)),
                ('tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_partida', to='app1.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='app1.partida')),
            ],
        ),
    ]
