# Generated by Django 4.2.3 on 2024-09-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_cartao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subst_lado', models.CharField(blank=True, choices=[('CASA', 'casa'), ('VISITANTE', 'visitante')], max_length=15, null=True)),
                ('tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jogador_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_entrou', to='app1.jogador')),
                ('jogador_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_saiu', to='app1.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='app1.partida')),
            ],
        ),
    ]
